#!/bin/bash
#
# Script to Undervolt/Overclock AMD Vega cards.
#
#  authored-by: Aaron Echols
#        email: atechols at gmail dot com
#
#  NOTES:
#
#  This script has been released under the GNU GENERAL PUBLIC LICENSE.
#  Please contribute to the upstream author at:
#  https://github.com/dasunsrule32/radeon-scripts
#
#  Install Instructions:
#
#  https://github.com/dasunsrule32/radeon-scripts/blob/master/systemd/INSTALL-vega-undervolt-oc.md
#

# Variables:
# ----------
DEBUG=0
SYSPATH=`find /sys/devices -name pp_od_clk_voltage 2>/dev/null | sed 's|/pp_od_clk_voltage||g' |head -n1`
KERNELVER=$(awk -F. '{print $1$2}' <<< `uname -r`)
KERNELREQ="415"
KERNELREQPOW="420"
POWERCAP="0" # Enable (1) or Disable (0) AMD powercap settings

# Functions:
# ----------
# Echo a string value that is passed
echo_text() {
   echo -e >&2 "$@";
}

# Main body:
# ----------
# Check if kernel version is new enough:
if [ $KERNELVER -lt $KERNELREQ ]; then
   echo_text "Kernel is too old, exiting..."
   exit 1
else
   echo_text "Kernel requirements met, continuing..."
fi

# Undervolt GPU:
echo "manual" > "$SYSPATH/power_dpm_force_performance_level"
echo "s 0 852 800" > "$SYSPATH/pp_od_clk_voltage"
echo "s 1 991 900" > "$SYSPATH/pp_od_clk_voltage"
echo "s 2 1084 910" > "$SYSPATH/pp_od_clk_voltage"
echo "s 3 1138 930" > "$SYSPATH/pp_od_clk_voltage"
echo "s 4 1200 945" > "$SYSPATH/pp_od_clk_voltage"
echo "s 5 1400 955" > "$SYSPATH/pp_od_clk_voltage"
echo "s 6 1500 970" > "$SYSPATH/pp_od_clk_voltage"
echo "s 7 1600 1000" > "$SYSPATH/pp_od_clk_voltage"

# Undervolt Memory:
echo "m 0 167 800" > "$SYSPATH/pp_od_clk_voltage"
echo "m 1 500 850" > "$SYSPATH/pp_od_clk_voltage"
echo "m 2 800 910" > "$SYSPATH/pp_od_clk_voltage"
echo "m 3 1000 1000" > "$SYSPATH/pp_od_clk_voltage"

# Set Power consumption - Requires Kernel 4.20+:
if [ $KERNELVER -ge $KERNELREQPOW ]; then
   if [ $DEBUG -eq 1 ]; then
      echo_text "Kernel Version: $KERNELVER"
   fi
   if [ $POWERCAP -eq 1 ]; then
      echo_text "Adjusting AMD  Power Cap"
      # To set the allowed maximum power consumption of the GPU to e.g. 220 Watts (Default wattage):
      echo 220000000 > /sys/class/drm/card0/device/hwmon/hwmon0/power1_cap
   fi
fi

# Commit Undervolt/OC changes:
echo "c" > "$SYSPATH/pp_od_clk_voltage"
